-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (p.price * sum(o.SALES_AMOUNT)) as SALES
FROM PRODUCT p join OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
group by p.PRODUCT_CODE
order by SALES desc, PRODUCT_CODE;
