-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, sum(o.AMOUNT*p.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT P LEFT JOIN FOOD_ORDER O
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE "2022-05%"
group by P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ;